import os
import json
import requests
import markdown

from pathlib import Path

API_KEY = os.environ["AZURE_FOUNDRY_API_KEY"]
ENDPOINT = os.environ["AZURE_FOUNDRY_ENDPOINT"]
DEPLOYMENT = os.environ["AZURE_FOUNDRY_DEPLOYMENT"]

DOCS = Path("docs")
DOCS.mkdir(exist_ok=True)

with open(
    "logs/openshift.log",
    "r",
    encoding="utf-8",
    errors="ignore"
) as f:
    log_content = f.read()

log_content = log_content[:100000]

SYSTEM_PROMPT = """
You are a Principal Performance Test Engineer and OpenShift Platform Architect.

Generate a professional stakeholder-ready report.

Output ONLY markdown.

# 🚀 OpenShift Log Analysis – Performance Test Report

## 1. Document Control

Create:

| Field | Value |
|---------|---------|
| Report Name | OpenShift Performance Analysis |
| Generated By | Azure AI Foundry |
| Environment | OpenShift |

---

## 2. Executive Summary

Provide:

- Overall Health
- Overall Verdict
- Top Findings
- Go / No-Go Recommendation

---

## 3. Test Objectives & Scope

Provide:

- What was tested
- Components analyzed
- Scope of analysis

---

## 4. System Under Test (SUT)

Create table:

| Component | Observation |

---

## 5. Performance Scorecard

Create table:

| Category | Score |
|------------|--------|
| Stability |
| Performance |
| Reliability |
| Resource Health |
| Availability |

Provide Overall Score.

---

## 6. Critical Findings

Create table:

| Severity | Issue | Impact |

---

## 7. Resource Utilization Analysis

### CPU Analysis

### Memory Analysis

### Network Analysis

### Storage Analysis

---

## 8. Pod Health Analysis

Create table:

| Pod | Issue | Severity | Recommendation |

---

## 9. Performance Metrics Analysis

Analyse:

- Average Response Time
- P90
- P95
- Error Rate
- Throughput

---

## 10. Root Cause Analysis

Issue
↓
Impact
↓
Root Cause

---

## 11. Recommendations

### Immediate Actions

### Short-Term Improvements

### Long-Term Improvements

---

## 12. Acceptance Criteria Summary

| Criteria | Target | Actual | Status |

---

## 13. Final Verdict

Use one of:

✅ PASS

⚠ PASS WITH OBSERVATIONS

❌ FAIL

Provide justification.

Return only markdown.
"""

payload = {
    "model": DEPLOYMENT,
    "messages": [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": log_content
        }
    ],
    "temperature": 0.2,
    "max_tokens": 3500
}

headers = {
    "api-key": API_KEY,
    "Content-Type": "application/json"
}

response = requests.post(
    f"{ENDPOINT}/chat/completions",
    headers=headers,
    json=payload,
    timeout=180
)

response.raise_for_status()

analysis = response.json()["choices"][0]["message"]["content"]

(DOCS / "summary.md").write_text(
    analysis,
    encoding="utf-8"
)

(DOCS / "analysis.json").write_text(
    json.dumps(
        {
            "analysis": analysis
        },
        indent=2
    ),
    encoding="utf-8"
)

html_report_body = markdown.markdown(
    analysis,
    extensions=["tables"]
)

html = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">

<title>OpenShift Log Analysis Performance Report</title>

<style>

body {{
    font-family: Segoe UI, Arial;
    background:#f5f7fa;
    margin:0;
    padding:30px;
}}

.container {{
    max-width:1400px;
    margin:auto;
}}

.header {{
    background:#c1121f;
    color:white;
    padding:25px;
    border-radius:10px;
}}

.header h1 {{
    margin:0;
}}

.report {{
    margin-top:20px;
    background:white;
    padding:30px;
    border-radius:10px;
    box-shadow:0 2px 12px rgba(0,0,0,.10);
}}

table {{
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
    margin-bottom:20px;
}}

table, th, td {{
    border:1px solid #cccccc;
}}

th {{
    background:#c1121f;
    color:white;
}}

th, td {{
    padding:10px;
}}

h1,h2,h3 {{
    color:#c1121f;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>🚀 OpenShift Log Analysis – Performance Test Report</h1>

<p>
Generated using Azure AI Foundry
</p>

</div>

<div class="report">

{html_report_body}

</div>

</div>

</body>

</html>
"""

(DOCS / "index.html").write_text(
    html,
    encoding="utf-8"
)

print("✅ summary.md created")
print("✅ analysis.json created")
print("✅ index.html created")
print("✅ Analysis completed successfully")
