import os
import json
import requests
from pathlib import Path

# ============================================================
# Azure AI Foundry Configuration
# ============================================================

API_KEY = os.environ["AZURE_FOUNDRY_API_KEY"]
ENDPOINT = os.environ["AZURE_FOUNDRY_ENDPOINT"]
DEPLOYMENT = os.environ["AZURE_FOUNDRY_DEPLOYMENT"]

# ============================================================
# Create docs folder
# ============================================================

DOCS = Path("docs")
DOCS.mkdir(exist_ok=True)

# ============================================================
# Read OpenShift Logs
# ============================================================

with open(
    "logs/openshift.log",
    "r",
    encoding="utf-8",
    errors="ignore"
) as f:
    log_content = f.read()

# Avoid sending extremely large logs
log_content = log_content[:100000]

# ============================================================
# AI Prompt
# ============================================================

SYSTEM_PROMPT = """
You are a Principal Performance Test Engineer and OpenShift Platform Architect.

Analyze the OpenShift logs and generate a professional report.

Use EXACTLY the structure below.

# 🚀 OpenShift Log Analysis – Performance Test Report

## 1. Document Control

Include:
- Report Name
- Generated Date
- Generated By
- Environment

---

## 2. Executive Summary

Provide:
- Overall Health
- Pass / Fail / Pass With Observations
- Top Findings
- Go / No-Go Recommendation

---

## 3. Test Objectives & Scope

Provide:
- What was tested
- Components involved
- Impacted services

---

## 4. System Under Test (SUT)

Provide a table:

| Component | Observation |

---

## 5. Performance Scorecard

Provide score from 0-100.

| Category | Score |
|-----------|-------|
| Stability |
| Performance |
| Reliability |
| Availability |
| Resource Health |

Provide:

Overall Score

---

## 6. Critical Findings

Provide table:

| Severity | Finding | Impact |

---

## 7. Resource Utilization Analysis

### CPU Analysis

### Memory Analysis

### Network Analysis

### Storage Analysis

---

## 8. Pod Health Analysis

Provide table:

| Pod | Issue | Severity | Recommendation |

---

## 9. Performance Metrics Analysis

Analyze:

- Average Response Time
- P90
- P95
- Error Rate
- Throughput

If unavailable mention "Not Available".

---

## 10. Root Cause Analysis

Issue
↓
Impact
↓
Root Cause

Provide detailed engineering explanation.

---

## 11. Recommendations

### Immediate Actions

### Short-Term Improvements

### Long-Term Improvements

---

## 12. Acceptance Criteria Summary

Provide table:

| Criteria | Target | Actual | Status |

---

## 13. Final Verdict

Choose only one:

✅ PASS

⚠ PASS WITH OBSERVATIONS

❌ FAIL

Provide justification.

Return markdown only.
"""

# ============================================================
# Request Payload
# ============================================================

payload = {
    "model": DEPLOYMENT,
    "messages": [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": log_content
        }
    ],
    "temperature": 0.2,
    "max_tokens": 3500
}

headers = {
    "api-key": API_KEY,
    "Content-Type": "application/json"
}

# ============================================================
# Azure AI Foundry Call
# ============================================================

print("Calling Azure AI Foundry...")

response = requests.post(
    f"{ENDPOINT}/chat/completions",
    headers=headers,
    json=payload,
    timeout=180
)

response.raise_for_status()

analysis = response.json()["choices"][0]["message"]["content"]

print("Analysis received successfully.")

# ============================================================
# Save Markdown Report
# ============================================================

(DOCS / "summary.md").write_text(
    analysis,
    encoding="utf-8"
)

# ============================================================
# Save JSON Report
# ============================================================

(DOCS / "analysis.json").write_text(
    json.dumps(
        {
            "analysis": analysis
        },
        indent=2
    ),
    encoding="utf-8"
)

# ============================================================
# Generate HTML Dashboard
# ============================================================

html = f"""
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>OpenShift Performance Test Report</title>

<style>

body {{
    font-family: "Segoe UI", Arial, sans-serif;
    background:#f4f6f9;
    margin:0;
    padding:25px;
}}

.container {{
    max-width:1400px;
    margin:auto;
}}

.header {{
    background:linear-gradient(135deg,#c1121f,#8d0801);
    color:white;
    padding:30px;
    border-radius:12px;
    margin-bottom:20px;
}}

.header h1 {{
    margin:0;
}}

.header p {{
    margin-top:10px;
}}

.cards {{
    display:flex;
    flex-wrap:wrap;
    gap:15px;
    margin-bottom:20px;
}}

.card {{
    flex:1;
    min-width:220px;
    background:white;
    padding:20px;
    border-radius:10px;
    box-shadow:0px 2px 8px rgba(0,0,0,0.10);
}}

.card-title {{
    color:#666;
    font-size:14px;
}}

.card-value {{
    color:#c1121f;
    font-size:22px;
    font-weight:bold;
    margin-top:5px;
}}

.report {{
    background:white;
    padding:30px;
    border-radius:12px;
    box-shadow:0px 2px 8px rgba(0,0,0,0.10);
}}

.report h2 {{
    color:#c1121f;
}}

.report-content {{
    white-space:pre-wrap;
    line-height:1.8;
}}

.footer {{
    text-align:center;
    margin-top:20px;
    color:#666;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">
    <h1>🚀 OpenShift Log Analysis Performance Report</h1>
    <p>Generated using Azure AI Foundry</p>
</div>

<div class="cards">

    <div class="card">
        <div class="card-title">Analysis Engine</div>
        <div class="card-value">Azure AI Foundry</div>
    </div>

    <div class="card">
        <div class="card-title">Platform</div>
        <div class="card-value">OpenShift</div>
    </div>

    <div class="card">
        <div class="card-title">Report Type</div>
        <div class="card-value">Performance Analysis</div>
    </div>

    <div class="card">
        <div class="card-title">Status</div>
        <div class="card-value">Completed</div>
    </div>

</div>

<div class="report">

<h2>Performance Assessment Report</h2>

<div class="report-content">
{analysis}
</div>

</div>

<div class="footer">
Generated Automatically Using Azure AI Foundry and GitHub Actions
</div>

</div>

</body>
</html>
"""

(DOCS / "index.html").write_text(
    html,
    encoding="utf-8"
)

print("✅ summary.md created")
print("✅ analysis.json created")
print("✅ index.html created")
print("✅ Analysis completed successfully")
