name: OpenShift AI Analysis

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Verify Repository Structure
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Structure:"
          ls -R

      - name: Analyse OpenShift Logs
        env:
          AZURE_FOUNDRY_API_KEY: ${{ secrets.AZURE_FOUNDRY_API_KEY }}
          AZURE_FOUNDRY_ENDPOINT: ${{ secrets.AZURE_FOUNDRY_ENDPOINT }}
          AZURE_FOUNDRY_DEPLOYMENT: ${{ secrets.AZURE_FOUNDRY_DEPLOYMENT }}
        run: |
          python scripts/analyse_openshift_logs.py

      - name: Verify Generated Files
        run: |
          echo "Generated Files"
          ls -lrt docs/

      - name: Publish Analysis To Summary
        run: |
          cat docs/summary.md >> $GITHUB_STEP_SUMMARY

      - name: Add Dashboard Link
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 🌐 OpenShift Analysis Dashboard" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[Click Here To Open Dashboard](https://abhireddi7823.github.io/OPENSHIFT-LOG-ANALYSIS/)" >> $GITHUB_STEP_SUMMARY

      - name: Upload Analysis Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenShift-AI-Analysis
          path: docs/
